POST http://web.socem.plymouth.ac.uk/COMP2001/KNouchin/Auth/user/
Content-Type: application/json
Accept: application/json
api_key: d7doDDgkyEqTuviyYEPi8w==

{
	"firstName":"Khodadad",
	"lastName":"Nouchin",
	"email":"xtrendence@gmail.com",
	"password":"test1ng"
}