PUT http://web.socem.plymouth.ac.uk/COMP2001/KNouchin/Auth/user/5
Content-Type: application/json
api_key: d7doDDgkyEqTuviyYEPi8w==

{
	"firstName":"Khodadad",
	"lastName":"Nouchin",
	"email":"xtrendence@gmail.com",
	"password":"anotherT3st"
}