POST https://localhost:44327/user
Content-Type: application/json
Accept: application/json
api_key: 2MX018IkPk6nhTXqHLQQMw==

{
	"firstName":"Khodadad",
	"lastName":"Nouchin",
	"email":"xtrendence@gmail.com",
	"password":"test1ng"
}