PUT https://localhost:44327/api/user/5
Content-Type: application/json
api_key: 2MX018IkPk6nhTXqHLQQMw==

{
	"firstName":"Khodadad",
	"lastName":"Nouchin",
	"email":"xtrendence@gmail.com",
	"password":"anotherT3st"
}